//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspriation.LibAPIS.API_Security {
    
    
    public partial class IA_GET_NEWTOKEN {
    }
}
