USE [master]
GO

/****** Object:  Database [Inspriation.BasicDB]    Script Date: 06/17/2014 15:54:29 ******/
CREATE DATABASE [Inspriation.BasicDB] ON  PRIMARY 
( NAME = N'Inspriation.BasicDB', FILENAME = N'C:\Users\SIKE\SkyDrive\ÎÄµµ\Inspriation\DataBase\DBFile\Inspriation.BasicDB.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Inspriation.BasicDB_log', FILENAME = N'C:\Users\SIKE\SkyDrive\ÎÄµµ\Inspriation\DataBase\DBFile\Inspriation.BasicDB_log.ldf' , SIZE = 3072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Inspriation.BasicDB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Inspriation.BasicDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Inspriation.BasicDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Inspriation.BasicDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Inspriation.BasicDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Inspriation.BasicDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Inspriation.BasicDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Inspriation.BasicDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Inspriation.BasicDB] SET  READ_WRITE 
GO

ALTER DATABASE [Inspriation.BasicDB] SET RECOVERY FULL 
GO

ALTER DATABASE [Inspriation.BasicDB] SET  MULTI_USER 
GO

ALTER DATABASE [Inspriation.BasicDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Inspriation.BasicDB] SET DB_CHAINING OFF 
GO


